#!/bin/bash
#PBS -q rt_HG
#PBS -l select=1
#PBS -l walltime=36:00:00
#PBS -P gcb50389

module purge
module load cuda/12.8 python/3.12
export CUDA_VISIBLE_DEVICES=$(
  nvidia-smi --query-gpu=index,uuid --format=csv,noheader |
  awk -v U="$CUDA_VISIBLE_DEVICES" 'BEGIN{gsub(/ /,"",U)} $2==U{print $1}'
)
source env_vllm/bin/activate
cd CodeGeeX

python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_go.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_java.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_js.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_python.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_rust.jsonl

python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_cpp.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_java.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_js.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_python.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_rust.jsonl

python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_go.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_cpp.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_js.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_python.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_rust.jsonl

python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_go.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_java.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_cpp.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_python.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_rust.jsonl

python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_go.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_java.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_js.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_cpp.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_rust.jsonl

python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_go.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_java.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_js.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_python.jsonl
python codegeex/benchmark/humaneval-x/translate_humaneval_x_vllm.py --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_cpp.jsonl