#!/bin/bash
export CUDA_VISIBLE_DEVICES=0
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_go.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_java.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_js.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_python.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/cpp/evaluation/humaneval_cpp_to_rust.jsonl

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_cpp.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_java.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_js.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_python.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/go/evaluation/humaneval_go_to_rust.jsonl

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_go.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_cpp.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_js.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_python.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/java/evaluation/humaneval_java_to_rust.jsonl

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_go.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_java.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_cpp.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_python.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/js/evaluation/humaneval_js_to_rust.jsonl

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_go.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_java.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_js.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_cpp.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 512 --output-file codegeex/benchmark/humaneval-x/python/evaluation/humaneval_python_to_rust.jsonl

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_go.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_java.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_js.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_python.jsonl
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path Qwen/Qwen3-Coder-30B-A3B-Instruct --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 512 --output-file codegeex/benchmark/humaneval-x/rust/evaluation/humaneval_rust_to_cpp.jsonl