#!/bin/bash
#PBS -q short-g
#PBS -l select=1
#PBS -W group_list=go25
#PBS -j oe
module purge
module load cuda/12.8
module load cudnn/9.10.1.4
module load nvidia/25.3
module load nv-hpcx/25.3
source /work/gj26/b20048/miniconda3/etc/profile.d/conda.sh
conda activate inference_env
export CUDA_VISIBLE_DEVICES=0
export PATH="$CONDA_PREFIX/bin:/opt/rh/gcc-toolset-14/root/usr/bin:$PATH"

export CC=/opt/rh/gcc-toolset-14/root/usr/bin/gcc
export CXX=/opt/rh/gcc-toolset-14/root/usr/bin/g++
export TRITON_CC="$CC"
export TRITON_CXX="$CXX"
export CUDAHOSTCXX="$CXX"

export PYTHONNOUSERSITE=1
cd CodeGeeX
# Qwen 3 Coder 0911 1616
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0116/humaneval_cpp_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0116/humaneval_cpp_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0116/humaneval_cpp_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0116/humaneval_cpp_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0116/humaneval_cpp_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0116/humaneval_go_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0116/humaneval_go_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0116/humaneval_go_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0116/humaneval_go_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0116/humaneval_go_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0116/humaneval_java_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0116/humaneval_java_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0116/humaneval_java_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0116/humaneval_java_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0116/humaneval_java_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0116/humaneval_js_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0116/humaneval_js_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0116/humaneval_js_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0116/humaneval_js_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0116/humaneval_js_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0116/humaneval_python_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0116/humaneval_python_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0116/humaneval_python_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0116/humaneval_python_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0116/humaneval_python_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0116/humaneval_rust_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0116/humaneval_rust_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0116/humaneval_rust_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0116/humaneval_rust_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0116/humaneval_rust_to_cpp.jsonl --samples-per-problem 1

# Qwen3 coder 0911 3232
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/drgrpo_0116/humaneval_cpp_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/drgrpo_0116/humaneval_cpp_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/drgrpo_0116/humaneval_cpp_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/drgrpo_0116/humaneval_cpp_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/drgrpo_0116/humaneval_cpp_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/drgrpo_0116/humaneval_go_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/drgrpo_0116/humaneval_go_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/drgrpo_0116/humaneval_go_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/drgrpo_0116/humaneval_go_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/drgrpo_0116/humaneval_go_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/drgrpo_0116/humaneval_java_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/drgrpo_0116/humaneval_java_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/drgrpo_0116/humaneval_java_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/drgrpo_0116/humaneval_java_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/drgrpo_0116/humaneval_java_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/drgrpo_0116/humaneval_js_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/drgrpo_0116/humaneval_js_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/drgrpo_0116/humaneval_js_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/drgrpo_0116/humaneval_js_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/drgrpo_0116/humaneval_js_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/drgrpo_0116/humaneval_python_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/drgrpo_0116/humaneval_python_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/drgrpo_0116/humaneval_python_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/drgrpo_0116/humaneval_python_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/drgrpo_0116/humaneval_python_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/drgrpo_0116/humaneval_rust_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/drgrpo_0116/humaneval_rust_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/drgrpo_0116/humaneval_rust_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/drgrpo_0116/humaneval_rust_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_drgrpo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/drgrpo_0116/humaneval_rust_to_cpp.jsonl --samples-per-problem 1

# Qwen3 coder 0911
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/dapo_0116/humaneval_cpp_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/dapo_0116/humaneval_cpp_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/dapo_0116/humaneval_cpp_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/dapo_0116/humaneval_cpp_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/dapo_0116/humaneval_cpp_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/dapo_0116/humaneval_go_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/dapo_0116/humaneval_go_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/dapo_0116/humaneval_go_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/dapo_0116/humaneval_go_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/dapo_0116/humaneval_go_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/dapo_0116/humaneval_java_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/dapo_0116/humaneval_java_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/dapo_0116/humaneval_java_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/dapo_0116/humaneval_java_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/dapo_0116/humaneval_java_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/dapo_0116/humaneval_js_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/dapo_0116/humaneval_js_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/dapo_0116/humaneval_js_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/dapo_0116/humaneval_js_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/dapo_0116/humaneval_js_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/dapo_0116/humaneval_python_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/dapo_0116/humaneval_python_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/dapo_0116/humaneval_python_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/dapo_0116/humaneval_python_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/dapo_0116/humaneval_python_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/dapo_0116/humaneval_rust_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/dapo_0116/humaneval_rust_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/dapo_0116/humaneval_rust_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/dapo_0116/humaneval_rust_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_dapo_0116/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/dapo_0116/humaneval_rust_to_cpp.jsonl --samples-per-problem 1

# Qwen3 coder 0911
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_code/humaneval_cpp_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_code/humaneval_cpp_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_code/humaneval_cpp_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_code/humaneval_cpp_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_code/humaneval_cpp_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_code/humaneval_go_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_code/humaneval_go_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_code/humaneval_go_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_code/humaneval_go_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_code/humaneval_go_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_code/humaneval_java_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_code/humaneval_java_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_code/humaneval_java_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_code/humaneval_java_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_code/humaneval_java_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_code/humaneval_js_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_code/humaneval_js_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_code/humaneval_js_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_code/humaneval_js_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_code/humaneval_js_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_code/humaneval_python_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_code/humaneval_python_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_code/humaneval_python_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_code/humaneval_python_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_code/humaneval_python_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_code/humaneval_rust_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_code/humaneval_rust_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_code/humaneval_rust_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_code/humaneval_rust_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_code/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_code/humaneval_rust_to_cpp.jsonl --samples-per-problem 1

# Qwen3 coder 0911
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type cpp --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_md/humaneval_cpp_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type cpp --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_md/humaneval_cpp_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type cpp --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_md/humaneval_cpp_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type cpp --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_md/humaneval_cpp_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type cpp --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/cpp/grpo_0123_md/humaneval_cpp_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type go --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_md/humaneval_go_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type go --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_md/humaneval_go_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type go --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_md/humaneval_go_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type go --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_md/humaneval_go_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type go --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/go/grpo_0123_md/humaneval_go_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type java --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_md/humaneval_java_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type java --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_md/humaneval_java_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type java --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_md/humaneval_java_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type java --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_md/humaneval_java_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type java --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/java/grpo_0123_md/humaneval_java_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type js --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_md/humaneval_js_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type js --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_md/humaneval_js_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type js --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_md/humaneval_js_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type js --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_md/humaneval_js_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type js --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/js/grpo_0123_md/humaneval_js_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type python --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_md/humaneval_python_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type python --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_md/humaneval_python_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type python --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_md/humaneval_python_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type python --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_md/humaneval_python_to_cpp.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --language-src-type python --language-tgt-type rust --batch-size 128 --output-file codegeex/benchmark/humaneval-x/python/grpo_0123_md/humaneval_python_to_rust.jsonl --samples-per-problem 1

python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/go/data/humaneval_go.jsonl.gz --language-src-type rust --language-tgt-type go --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_md/humaneval_rust_to_go.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/java/data/humaneval_java.jsonl.gz --language-src-type rust --language-tgt-type java --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_md/humaneval_rust_to_java.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/js/data/humaneval_js.jsonl.gz --language-src-type rust --language-tgt-type js --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_md/humaneval_rust_to_js.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/python/data/humaneval_python.jsonl.gz --language-src-type rust --language-tgt-type python --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_md/humaneval_rust_to_python.jsonl --samples-per-problem 1
python -m codegeex.benchmark.humaneval-x.translate_humaneval_x_vllm --model-name-or-path /work/go25/share/model/Qwen2.5_Coder_7B_grpo_0123_md/checkpoint-68 --src-path codegeex/benchmark/humaneval-x/rust/data/humaneval_rust.jsonl.gz --tgt-path codegeex/benchmark/humaneval-x/cpp/data/humaneval_cpp.jsonl.gz --language-src-type rust --language-tgt-type cpp --batch-size 128 --output-file codegeex/benchmark/humaneval-x/rust/grpo_0123_md/humaneval_rust_to_cpp.jsonl --samples-per-problem 1
